exception great


http://libvirt.org/git/?p=libvirt-test-API.git;a=blob;f=src/exception.py;h=70d0175e49dafc83ba190cf398e02639041d0498;hb=HEAD


http://libvirt.org/git/?p=libvirt-test-API.git;a=blob;f=utils/utils.py;h=147c1ef7014f331b1e664f3c8f407853555a74b9;hb=HEAD

http://libvirt.org/git/?p=libvirt-test-API.git;a=blob;f=utils/log.py;h=4111fd9de00ab0341ed49aeb2d6481c620471cba;hb=HEAD
